# set -g default-shell $SHELL 
# set -g default-command "reattach-to-user-namespace -l ${SHELL}"
setw -g mode-keys vi
# set-option -g mouse on
set -g set-clipboard off

#-- bindkeys --#

set -g prefix ^b
unbind ^a
bind b send-prefix
bind u source-file ~/.tmux.conf

######################
### DESIGN CHANGES ###
######################

# The statusbar {

set -g status-position bottom
set -g status-bg default
set -g status-fg colour137
set -g status-attr dim
set -g status-justify centre
set -g status-left ''
set -g status-right '#[fg=colour233,bg=colour241,bold] %m/%d #[fg=colour233,bg=colour246,bold] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 20
# set -g message-fg colour232
set -g message-bg colour149

setw -g window-status-current-fg colour82
setw -g window-status-current-bg colour66
setw -g window-status-current-attr bold
setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour82]#F '

setw -g window-status-fg colour2
setw -g window-status-bg colour237
setw -g window-status-attr none
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

setw -g window-status-bell-attr bold
setw -g window-status-bell-fg colour255
setw -g window-status-bell-bg colour1

if-shell "[[ "$ITERM_PROFILE" == "light" ]]" \
    "setw -g window-status-current-fg colour82; setw -g window-status-current-bg colour144; setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour230]#W#[fg=colour82]#F '; \
     setw -g window-status-fg colour2; setw -g window-status-bg colour144; setw -g window-status-format ' #I#[fg=colour230]:#[fg=colour230]#W#[fg=colour230]#F ';\
     set -g status-right '#[fg=colour230,bg=colour144,bold] %d/%m #[fg=colour230,bg=colour149,bold] %H:%M:%S ';\
     set -g message-bg colour149"
# }
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @resurrect-strategy-vim 'session'
# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
